### PR TITLE
fix: ledger wallet

### LINKED ISSUE #497: ChainProvider ledger: TypeError: this.client.getOfflineSigner is not a function
Getting error when trying to sign a txn after connecting ChainProvider to ledger 

```
chain-wallet.js:220 Uncaught (in promise) TypeError: this.client.getOfflineSigner is not a function
    at LedgerChianWallet.initOfflineSigner (chain-wallet.js:220:48)
    at getSigningCosmWasmClient (chain-wallet.js:233:24)
```

├── @cosmjs/amino@0.32.4
├── @cosmjs/cosmwasm-stargate@0.32.4
├── @cosmjs/proto-signing@0.32.4
├── @cosmjs/stargate@0.32.4
├── @cosmos-kit/leap-extension@2.12.2
├── @cosmos-kit/react@2.18.0

### PR DESCRIPTION
**Pull request by fmorency**
- Fixes the missing `getOfflineSigner` implementation
- Fixes `StdSignDoc` serialization to JSON. The object MUST be serialized in lexicographical key order [1]
- Replace the encoding of `pubkey` in `getAccount` from a `TextEncoder` to using the `fromHex` function
- Bump `@ledgerhq/*` dependencies
- Prettify

Fixes #497 

[1]: https://github.com/cosmos/ledger-cosmos/blob/main/docs/TXSPEC.md#validation

### CODE REVIEW

File: wallets/ledger/src/web-usb-hid/chain-wallet.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { ChainRecord, ChainWalletBase, Wallet } from '@cosmos-kit/core';
 
-export class LedgerChianWallet extends ChainWalletBase {
+export class LedgerChainWallet extends ChainWalletBase {
```
Comment (fmorency) [inline wallets/ledger/src/web-usb-hid/chain-wallet.ts:3]: Fix typo and prettify

File: wallets/ledger/src/web-usb-hid/client.ts [hunk 2]
```diff
@@ -39,16 +47,44 @@ export class LedgerClient implements WalletClient {
       username: username ?? path,
       address,
       algo: 'secp256k1' as Algo,
-      pubkey: new TextEncoder().encode(publicKey),
+      pubkey: fromHex(publicKey),
```
Comment (fmorency) [inline wallets/ledger/src/web-usb-hid/client.ts:50]: We want the publicKey as an hex byte array, not a UTF-8 byte array

**Comment by fmorency** [comment]
Only `accountIndex=0` seems supported. I'm not sure if other indices were ever supported.

**Comment by pyramation** [comment]
Thanks so much @fmorency :)
